### ISSUE TITLE
Move kibbo to use labels instead of env

### ISSUE THREAD

**Issue by ahmad-musleh** [ahmad-musleh/kibbo#17]
Currently, we have:
```yaml
services:
  kibbo:
    environment:
      - APPEND=TRUE
      - INCLUDE_TIMESTAMPS=TRUE
```

While this gets the job done, it is some what limited to the kibbo service. A more uniform approach is using labels for different configurations. This would also allow configurations to be set from other services in the project. We can have something like the following instead:

```yaml
services:
  kibbo:
    labels:
      - kibbo.config.log_mode=optout
      - kibbo.config.log_file_update_mode=replace
```

The way to implement this would be to have an opt-in/opt-out option where by you have choice with the norm and exception. 

# opt-out (Default)

Opting out would be to log all services by default. The norm being all services and the exception being to choose a specific service you do not want logged.

# opt-in

With opt-in, the norm would be to not log any services and the exception being logging only whats specified.

# Implementation

- Phase 1: Implement opt-out logic
  - opt-out setup
  - appending to log file
  - timestamps  
- Phase 2: Implement opt-in logic
  - opt-in setup
  - appending to log file
  - timestamps

# Release

This will most likely result in a major release due to dropping support for env variables of appending and timestamps.
