### ISSUE TITLE
Documentation/Compose file do not use image deployed

### ISSUE THREAD

**Issue by ahmad-musleh** [ahmad-musleh/kibbo#2]
Should be 

```yaml
version: "3"
services:
  kibbo:
    image: musleh/kibbo:1.0.0
```
