### ISSUE TITLE
Add example service to browser compose 

### ISSUE THREAD

**Issue by ahmad-musleh** [ahmad-musleh/kibbo#35]
Add an example service to showcase how the service works. For example:

```yaml
services:
  example:
    image: hello-world:latest
    labels:
      - kibbo.config.logging.active=true
```
